### ISSUE TITLE
Android support 

### ISSUE THREAD

**Issue by waddles** [grantbeattie/plugin.video.nineau-catchup#2]
Addon doesn't seem to work on Kodi 14 on Android. Browsing episodes works but unable to play anything

**Comment by grantbeattie** [comment]
I'm guessing this is the same as previous xbmc releases where the Android build doesn't include gnutls support.

Have you tried enabling compatibility mode in the addon settings?

**Comment by grantbeattie** [comment]
Confirmed fixed by enabling SSL compatibility for Android and older XBMC releases.

**Comment by waddles** [comment]
Nope, not fixed. See https://gist.github.com/waddles/00e3606d4d133cd8608d

**Comment by grantbeattie** [comment]
You're on 15.2 - you don't need the HLS compatibility mode enabled. Disable it and it should work as expected.

(works for me on 15.1)
